version: '2'
services:
  benthos-in:
    image: jeffail/benthos
    environment:
      BENTHOS_INPUT: "http_server"
      HTTP_SERVER_INPUT_ADDRESS: "0.0.0.0:8080"
      BENTHOS_OUTPUT: "amqp"
      AMQP_OUTPUT_URL: "amqp://guest:guest@rabbitmq:5672/"
      AMQP_OUTPUT_EXCHANGE: "benthos-exchange"
      AMQP_OUTPUT_EXCHANGE_TYPE: "direct"
      AMQP_OUTPUT_QUEUE: "benthos-stream"
      AMQP_OUTPUT_KEY: "benthos-key"
      AMQP_OUTPUT_CONSUMER_TAG: "benthos-consumer"
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
